#spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/...
#    password:...
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update

#manual step
spring:
  profiles:
    active:
      - dev


#configured in pom.xml under profiles
#spring:
#  profiles:
#    active: @spring.profiles.active@